HartiganHM/game-time

index.html
lib/Block.js
lib/Paddle.js
lib/index.js

- Added if statements to block.move() to detect paddle presence
- Increased paddle width and speed for more effective testing and playability
- Removed canvas bottom boundary for 'Game Over' possibilty
Notes:
- File types need further specification and cleaning up
- Get rid of nested if statements with SRP methods/functions
- Dumb down objects with more general child elements that inherit from parent methods
- General code clean-up with indentation and syntax checks

Paddle collision

---

index.html
lib/Ball.js
lib/Blocks.js
lib/index.js
package-lock.json

got the for loop for our bricks to display.

got all the blocks to show up

---

lib/Game.js
lib/index.js

- Fixed missing file for merge

Js file split

---

lib/Ball.js

Got the ball to stop and the block of the blocks, and not go to the very top of the canvas.

ball stops at the top of the blocks and not top of canvas

---

lib/Ball.js
lib/Paddle.js
lib/index.js

- Added left and right boundaries for the paddle to keep it in play area
- Commented out page reload for testing purposes, will add back when game restart is more functional

Paddle boundary

---

lib/Ball.js
lib/Game.js
lib/Paddle.js
lib/SquarePiece.js
lib/index.js

- Added keyup listener on window for cleaner key controls
- Relocated paddle.move() method to game for smoother paddle visual movement
- Added `return this` to SquarePiece.js for method chaining in Game.js
- Added extra paddle properties for friction, speed, velocity
- Refactored Paddle.move() method to have Paddle.edgeCheck() for canvas edge check
- Removed old paddle boundary code
- Reduced paddle speed for easier gameplay

Paddle control adjustments

---

lib/Ball.js

- Removed code so ball/paddle collision was more accurate

Fixed ball and paddle collision to be more accurate

---

.eslintrc.json
lib/Ball.js
lib/Game.js
lib/Paddle.js
lib/index.js
package-lock.json
package.json

eslint installed

---

lib/Ball.js
lib/Game.js
lib/SquarePiece.js

When blocks are hit they are removed from the block array, and score now appears at the top.

blocks are removed when hit, and score is added

---

lib/Ball.js
lib/Game.js

- Changed ball x velocity for different sections of the paddle
- Increased overall ball velocity to 5

Paddle ball velocity change

---

lib/Game.js
lib/SquarePiece.js

Scoring is working and updating.

scoring system works

---

lib/Ball.js
lib/Game.js
lib/SquarePiece.js

score functionality is working, and lives is showing up, but still need to create the functionality for it.

added score functioanlity started lives functionality

---

game.css
index.html
lib/Game.js
lib/SquarePiece.js
lib/images/blue-brick.svg
lib/images/paddle.svg

**NOTE: Mistakenly used wrong branch name, changes on branch are for images only**
- Added images folder to repo
- Added SVG images for paddle and bricks
- Added drawImage function to draw method which takes an image in as an argument
- Added img HTML elements for stored images and set CSS styling to display none
- Increased size of paddle for testing

Brick and Paddle Images

---

lib/Game.js
lib/Player.js
lib/SquarePiece.js
lib/index.js

added lives and takes away from total lives.

Reset lives

---

index.html
lib/Ball.js
lib/Game.js
lib/SquarePiece.js

- Changed canvas dimension for better testing
- Adjusted top canvas boundary for new canvas dimensions
- Adjusted top and bottom brick collision to be more accurate by including ball radius
- Refactored Ball.move() to Ball.paddleHit() for cleaner code
- Began Ball.paddleSideHit() but waiting for new branch

Brick side collision

---

lib/Ball.js
lib/Game.js
lib/Paddle.js
lib/Player.js
lib/SquarePiece.js
lib/index.js
package-lock.json
package.json

- Pulled canvas edge check out of ball.move() method and built ball.edgeCheck() method
- Changed ball starting position on canvas
- Called ball.move() on player death

Ball canvas refactor

---

game.css
lib/Game.js
lib/Player.js
lib/index.js

background and start

---

test/paddle-test.js

- Added beforeEach to test environment in paddle-test.js
- Finished running tests for basic class properties and methods

Paddle test

---

lib/Player.js
test/player-test.js
test/squarePiece-test.js

player tested completed. Square piece still needs some work

player test almost done and squarePiece

---

lib/Ball.js
lib/Game.js

- Styled ball with gradient
- Set font fillStyle to black

Ball style

---

lib/Ball.js
lib/Game.js
lib/index.js

- Added cheatcodes to choose level at Game Start

Cheatcodes

---

lib/Ball.js
lib/Game.js
lib/Player.js
lib/SquarePiece.js
test/player-test.js
test/squarePiece-test.js

Clean-up after Eval by Combat
- Refactored squarePiece.collide method to eliminate game, index, and blockArr arguments
- Refactored code for brick removal and score change into game.js
- Pass squarePiece collide method test
- Refactored duplicate code into ball.reset method
- Refactored death check to eliminate canvas and game arguments
- Passed player deathCheck method test

Eval tests

---

test/ball-test.js
test/paddle-test.js
test/player-test.js
test/squarePiece-test.js

- Renamed test files to correspond to actual .js files
- Added describe functions to all test files

Renamed files and added describe functions

---

lib/Game.js
lib/index.js

- Added labels to event listeners in index.js
- Added widen paddle cheat code
- Started building war cheat code

Cheatcodes 2

---

lib/Game.js
lib/index.js

- Moved sound file to index.js
- Added introSound play on load and pause on game start

Sound implementation

---

lib/Game.js
lib/index.js

- Renamed song files for easier usability
- Changed intro song file path in index.js
- Called other two songs in Game.js

Sound implementation 2
